name: Keep Application Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send first request to keep application alive
        run: |
          curl -X GET "https://deployment-1-99ih.onrender.com/"

      - name: Send second request to keep application alive
        run: |
          curl -X GET "https://deployment-rsku.onrender.com/"
