name: Send request every 2 minutes

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  send_request:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Dietwell
        run: |
          response=$(curl -X GET -s -o /dev/null -w "%{http_code}" https://dietwell-5gr8.onrender.com/)
          echo "Response: $response"
