name: Keep Application Alive

on:
  schedule:
    # Runs every 14 minutes
    - cron: '*/14 * * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send first request to keep application alive
        run: |
          curl -X GET "https://deployment-npko.onrender.com/"

      - name: Send second request to keep application alive
        run: |
          curl -X GET "https://deployment-9cai.onrender.com/"
